accounts/urls.py
from django.urls import path
# from django.contrib import admin
from .import views 

app_name = 'accounts'

urlpatterns = [
	path('signup', views.signup_view, name="signup"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout")	
]

articles/urls.py
from django.urls import path
# from django.contrib import admin
from .import views 


app_name = 'articles'

urlpatterns = [
	path('', views.article_list, name='list'),
	path('create', views.article_create, name='create'),
	path('<slug:slug>/', views.detail , name='detail')
]

djangonautic/urls.py
from django.urls import include, path 
from django.contrib import admin
from .import views 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'), name='articles'),
    path('about/<int:slug>/', views.about),
    path('accounts/', include('accounts.urls')),
    path('', article_views.article_list, name='home')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
	

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + "..."

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ['title', 'body', 'slug']
		

accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout 

# Create your views here.
def signup_view(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			# log user in
			login(request, user)
			return redirect('articles:list')
	else: 
		form = UserCreationForm() 

	return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log in user
			user = form.get_user()
			login(request, user)
			if 'next' in request.POST:
			 	return redirect(request.POST.get('next'))
			else: 
				return redirect('articles:list')
	else: 
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect 
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms 

# Create your views here.
def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request, 'articles/article_list.html', {'articles': articles})

def detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug= slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login")
def article_create(request):
	if request.method == 'POST':
		form = forms.CreateArticle(request.POST, request.FILES)
		if form.is_valid:
			#save article to db
			instance = form.save(commit=False)
			instance.author = request.user 
			instance.save()
			return redirect('articles:list')
	else: 
		form = forms.CreateArticle()
	return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

#Function that will fire off when user visits homepage
def homepage(request):
	# return HttpResponse("HOME")
	return render(request, 'homepage.html')

#Function for when user visits /about url
def about(request):
	# return HttpResponse(slug)
	return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
	<h1>Log In</h1>
	<form class="site-form" action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
		{{form}}
		{% if request.GET.next %}
			<input type="hidden" name="next" value="{{request.GET.next}}"> 
		{% endif %}	
		<input type="submit" value="Login">
	</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
	<h1>Sign Up</h1>
	<form class="site-form" action="/accounts/signup" method="post">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="Signup">
	</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
	<div class=" row create-article">
		<h3 class="row">Create Awesome New Article</h3>
		<form class="site-form row" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form }}
			<input type="submit" value="Create" />
		</form>
	</div>	
{% endblock %}

articles/templates/articles/article_detail.html
{%  extends 'base_layout.html' %}

{% block content %}

	<div class="article-detail">
		<div class="article">
			<h2>{{article.title}}</h2>
			<p>{{article.body}}</p>
			<p>{{article.date}}</p>
			<p>By: {{article.author}}</p>
		</div>
	</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} {% block content %}
<div class="jumbotron text-center">
    <div class="container">
        <h1 class="display-4">Ride Diaries</h1>
        <p class="lead">Lift likes to say, "It matters how you get there." and whether you are getting there in an Uber or a Lyft the ride and the people you meet make for a story that is worth sharing.</p>
    </div>
</div>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p class="author">By: {{article.author}}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>Djangonautic</title>
</head>
<body>
	<h1>ABOUT PAGE</h1>
	<p>This is the about page</p>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Ride Diaries</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet"> 

	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
	<body>
		<header >
			<nav class="navbar">
				<h1><a class="home" href="{% url  'home' %}">home</a></h1>
					<ul class=" nav justify-content-end">
					{% if user.is_authenticated %}
						<li>
							<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
								{% csrf_token %}
								<button type="submit" class="btn">Logout</button>
							</form>
						</li>
						<li><a href="{% url 'articles:create' %}" class="highlight"><button  type="button" class="btn">New Article</button></a></li>
					{% else %}
						<li><a href="{% url 'accounts:login' %}"><button  type="button" class="btn">Login</button></a></li>
						<li><a href="{% url 'accounts:signup' %}"><button  type="button" class="btn">Signup</button></a></li>
					{% endif %}
					</ul>
			</nav>
		</header>
		<div class="wrapper">
			{% block content %}

			{% endblock %}
		</div>
	</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Djangonautic</title>
</head>
<body>
	<h1>HOMEPAGE</h1>
	<p>This is the homepage</p>
</body>
</html>